doctrine:
  orm:
    auto_mapping: true
    mappings:
      Page:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/zentlix/page-bundle/src/Domain/Page/Entity'
        prefix: Zentlix\PageBundle\Domain\Page\Entity